### PR TITLE
Feat: Add response template keys

### PR DESCRIPTION
**Pull request by MariaPushkin**
closes gravitee-io/issues#2208

### CODE REVIEW

**Comment by brasseld** [comment]
Hi @MariaPushkin 

Can you resolve the conflict here?

Thanks.

**Comment by brasseld** [comment]
Still in conflict state...

**Comment by MariaPushkin** [comment]
Sorry have problems with resolving, will try to recreate a new pull request

**Comment by brasseld** [comment]
ok, no worries!

**Pull request closed without merging**
